# ---- STAGE 1: build ----
FROM node:24.0.2 AS builder
WORKDIR /app

COPY package*.json ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# ---- STAGE 2: runtime ----
FROM node:24.0.2
WORKDIR /app

COPY --from=builder /app/prisma      ./prisma
COPY --from=builder /app/package.json ./package.json 
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production
EXPOSE 4000
CMD ["yarn", "start"]